### PR TITLE
Add test runs on JDK 11, 13

### PR DESCRIPTION
**Pull request by brastak**
For #17

### CODE REVIEW

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/go-adapter/issues/19#issuecomment-601746986))

@g4s8 Job `gh:artipie/go-adapter#19` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job [#19](https://github.com/artipie/go-adapter/issues/19) is closed, can't start order

**Comment by 0crat** [comment]
Job `gh:artipie/go-adapter#19` is not assigned, can't get performer

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Pull request merged**
